version: '3.8'
services:
  slack-bot:
    build: .
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    restart: unless-stopped
